### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by e2d2** [cul-it/rmc-workflow-scripts#24]
Ran script over documents and received following error: 
 Traceback (most recent call last):
  File "flagNames.py", line 65, in <module>
    main()
  File "flagNames.py", line 19, in main
    flagNames(idir, iout)
  File "flagNames.py", line 45, in flagNames
    outwrite.write('\t'.join([thisfile, f,]))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfd' in position 70: surrogates not allowed

**Comment by dd388** [comment]
I have to say, I have no idea what this is.

http://www.charbase.com/dcfd-unicode-invalid-character

But maybe we can mitigate what's happening...?!

**Comment by dd388** [comment]
Okay, try it now and if that breaks it really badly, let me know and we can roll it back and try again.

**Comment by pm66** [comment]
[http://www.fileformat.info/info/unicode/char/1f4fd/film_projector.png]It shows up in the second half of the 16 bit character  0xD83D 0xDCFD    [FILM PROJECTOR]

**Comment by dd388** [comment]
Huh. Interesting. Well, let's see what happens with testing an go from there.
