### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by e2d2** [cul-it/rmc-workflow-scripts#27]
Staff ran "runTriage.py" script on a batch of content. Received this error: 
```
bcadmin@bcadmin-Precision-T1650:~/Desktop/rmc-workflow-scripts/disk-image-triage$ python3 runTriage.py ~/Desktop/RMM08540
The size of the input directory is: 1G
To continue, you need 6G of free space.
Do you want to continue? y/N y
Traceback (most recent call last):
  File "runTriage.py", line 53, in <module>
    main()
  File "runTriage.py", line 47, in main
    guymagerLogMD(args.inputdir)
  File "/home/bcadmin/Desktop/rmc-workflow-scripts/disk-image-triage/guymagerLogMD.py", line 49, in guymagerLogMD
    for line in open(filename, 'rU'): 
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 4662: invalid start byte
bcadmin@bcadmin-Precision-T1650:~/Desktop/rmc-workflow-scripts/disk-image-triage$ ^C
```
Script had reorganized and started to pull data out of guymager logs but failed on some unicode in one of the guymager logs? I ran just the guymagerLogMD.py script and that gave me the same error.

**Comment by dd388** [comment]
typically the info file outputs as this: ASCII English text, with CRLF, LF line terminators

the ones that it's failing on are like this: ISO-8859 English text, with CRLF, LF line terminators

I'll work on a graceful way of handling various encodings.

**Comment by dd388** [comment]
Question: Were the titles pasted into the Guymager dialog box copied right from the Voyager client, perchance? I'm finding the `†` character in that field.

**Comment by dd388** [comment]
Workaround fix https://github.com/cul-it/rmc-workflow-scripts/commit/f2fc5652e2e01e7c62cbb3b3da5d01827dcd0869

Test it and let me know how it goes.
